apiVersion: batch/v1
kind: Job
metadata:
  # Unique key of the Job instance
  name: example-9-fuse
#   namespace: mem-example
spec:
  activeDeadlineSeconds: 1000
  template:
    metadata:
      name: example-job
    spec:
      containers:
      - name: pi
        image: us.gcr.io/glen-rl-framework/glen:latest
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
        lifecycle:
          postStart:
            exec:
              command: ["mkdir", "/bucket"]
              command: ["gcsfuse", "-o", "nonempty", "rl-framework-cluster-bucket ", "/bucket"]
          preStop:
            exec:
              command: ["fusermount", "-u", "/bucket"]
        resources:
          limits:
            cpu: 0.5
            memory: "1Gi"
          requests:
            cpu: 0.5
            memory: "1Gi"
        command: ["ls"]
        args: ["-l", "-a"]
      # Do not restart containers after they exit
      restartPolicy: Never
