apiVersion: batch/v1
kind: Job
metadata:
  # Unique key of the Job instance
  name: example-9-fuse
#   namespace: mem-example
spec:
  activeDeadlineSeconds: 1000
  containers:
  - name: pi
    image: us.gcr.io/glen-rl-framework/glen:latest
    resources:
      limits:
        cpu: 0.5
        memory: "1Gi"
      requests:
        cpu: 0.5
        memory: "1Gi"
    command: ["ls"]
    args: ["-l", "-a"]
    volumeMounts:
    - mountPath: /mnt/Cluster_Shared
      name: test-volume
  # Do not restart containers after they exit
  restartPolicy: Never
  volumes:
  - name: test-volume
    hostPath:
      path: /mnt/Cluster_Shared
