apiVersion: batch/v1
kind: Job
metadata:
  # Unique key of the Job instance
  name: example-15-nfs
#   namespace: mem-example
spec:
  template:
    metadata:
      name: example-job
    spec:
      activeDeadlineSeconds: 1000
      containers:
      - name: terrainrlgym
        image: us.gcr.io/glen-rl-framework/glen:latest
        # Write to a file inside our NFS
        command: ["/bin/sh"]
        args: ["-c", "date >> /mnt/test/dates.txt; cat /mnt/test/dates.txt"]
#        volumeMounts:
#          - name: nfs-volume
#            mountPath: /mnt/test
      # Do not restart containers after they exit
      restartPolicy: Never
        # Add the server as an NFS volume for the pod
      volumes:
        - name: nfs-volume
          nfs: 
          # URL for the NFS server
            server: 10.108.211.244 # Change this!
            path: /data
