apiVersion: batch/v1
kind: Job
metadata:
  # Unique key of the Job instance
  name: example-job3
spec:
  activeDeadlineSeconds: 100
  template:
    metadata:
      name: example-job
    spec:
      containers:
      - name: pi
        image: us.gcr.io/glen-rl-framework/glen:latest
        command: ["python3"]
        args: ["-c", "print('somethings')"]
      # Do not restart containers after they exit
      restartPolicy: Never
