apiVersion: batch/v1
kind: Job
metadata:
  # Unique key of the Job instance
  name: example-9-fuse
#   namespace: mem-example
spec:
  activeDeadlineSeconds: 1000
  containers:
  - name: pi
    image: us.gcr.io/glen-rl-framework/glen:latest
    resources:
      limits:
        cpu: 0.5
        memory: "1Gi"
      requests:
        cpu: 0.5
        memory: "1Gi"
    # Write to a file inside our NFS
    command: ["/bin/sh"]
    args: ["-c", "while true; do date >> /mnt/test/dates.txt; sleep 5; done"]
    volumeMounts:
    - mountPath: /mnt/test
      name: nfs-volume
  # Do not restart containers after they exit
  restartPolicy: Never
    # Add the server as an NFS volume for the pod
  volumes:
    - name: nfs-volume
      nfs: 
        # URL for the NFS server
        server: 10.108.211.244 # Change this!
		path: /data
